package fr.istic.m2il.aoc.observerasynchrone.channel;

import fr.istic.m2il.aoc.observerasynchrone.generator.Generator;

import java.util.concurrent.Callable;

/**
 * Represents Method Invocation of Generator.getValue() method of Generator
 */
public class GetValue implements Callable<Integer>{

    private Generator generator;

    public GetValue(Generator generator) {
        this.generator = generator;
    }

    /**
     * Gets the newest value generated by the generator asynchronously
     * @return value of generator.getValue() method synchronously
     */
    private Integer getValue(){
        return generator.getValue();
    }

    @Override
    public Integer call() throws Exception {
        return getValue();
    }
}
